### ISSUE TITLE
Add pre-commit configuration - [merged]

### ISSUE THREAD

**Issue by juan-pe** [somcomunitats-coop/odoo-ec#200]
***In GitLab by @konykon on Jul 17, 2023, 13:30 GMT+2:***

_Merges feature/add-precommit-configuration -> dev_

**Assignees:** konykon

**Reviewers:** benjami

**Approved by:** DaniilDigtyar

*Migrated from GitLab: https://git.coopdevs.org/coopdevs/comunitats-energetiques/odoo-ce/-/merge_requests/160*

**Comment by juan-pe** [comment]
***In GitLab by @konykon on Jul 17, 2023, 13:42 GMT+2:***

added 1 commit

<ul><li>97255c8d - Add linters configuration</li></ul>

[Compare with previous version](/coopdevs/comunitats-energetiques/odoo-ce/-/merge_requests/160/diffs?diff_id=22452&start_sha=fe3df158ee0e772a2b069755ca4a753824765fa3)

**Comment by juan-pe** [comment]
***In GitLab by @konykon on Jul 17, 2023, 13:54 GMT+2:***

added 1 commit

<ul><li>fe15e47d - Update black version</li></ul>

[Compare with previous version](/coopdevs/comunitats-energetiques/odoo-ce/-/merge_requests/160/diffs?diff_id=22453&start_sha=97255c8d011b70b8c74f28ddb2c3260b26dd9f0b)

**Comment by juan-pe** [comment]
***In GitLab by @DaniilDigtyar on Jul 17, 2023, 17:21 GMT+2:***

Does this apply itself, or do we need to execute the pre-commit command like in OCA?

**Comment by juan-pe** [comment]
***In GitLab by @DaniilDigtyar on Jul 17, 2023, 17:23 GMT+2:***

Okey :sweat_smile:, didn't see the other MR with the documentation 
https://git.coopdevs.org/coopdevs/comunitats-energetiques/documentacio/-/merge_requests/1

**Comment by juan-pe** [comment]
**Discussion in GitLab:**

***In GitLab by @DaniilDigtyar on Jul 17, 2023, 17:28 GMT+2:***

I see that the pipelines are failing, is this normal? I can't figure out where is the problem.
https://git.coopdevs.org/coopdevs/comunitats-energetiques/odoo-ce/-/pipelines/36100/failures

***In GitLab by @konykon on Jul 17, 2023, 17:39 GMT+2:***

The last few pipelines are failing, i don´t think it is relevant with this MR. Maybe we have to update the unavailable package on gitlab-ci or check their server status.

***In GitLab by @konykon on Jul 19, 2023, 12:32 GMT+2:***

fixed!

**Comment by juan-pe** [comment]
***In GitLab by @konykon on Jul 19, 2023, 12:32 GMT+2:***

resolved all threads

**Comment by juan-pe** [comment]
***In GitLab by @konykon on Jul 19, 2023, 12:32 GMT+2:***

requested review from @benjami

**Comment by juan-pe** [comment]
**Discussion in GitLab:**

***In GitLab by @DaniilDigtyar on Jul 19, 2023, 13:59 GMT+2:***

Tried running as the documentation says and found this problem. I tried with a new commit and running manually.
https://git.coopdevs.org/coopdevs/comunitats-energetiques/documentacio/-/snippets/39


```
error in pylint setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.5.*'
```

***In GitLab by @DaniilDigtyar on Aug 7, 2023, 10:57 GMT+2:***

This was solved by moving the pylint-odoo to his own repo and hook

```yaml
  - repo: https://redirect.github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        name: pylint with optional checks
        args:
          - --rcfile=.pylintrc
          - --exit-zero
        verbose: true
      - id: pylint
        name: pylint with mandatory checks
        args:
          - --rcfile=.pylintrc-mandatory
  - repo: https://redirect.github.com/OCA/pylint-odoo
    rev: v8.0.19
    hooks:
      - id: pylint_odoo
        name: pylint odoo
```
